spring:
  application:
    name: allocator
  datasource:
    url: jdbc:postgresql://localhost:5432/tequipy
    username: tequipy
    password: tequipy
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
